spring:
  profiles:
    active: local
    group:
        local: gpt, local-db
        deploy: gpt, eb-db
  thymeleaf:
    prefix: classpath:/templates/   #spring.mvc.static-path-pattern=/static/**
    servlet:
      produce-partial-output-while-processing: false # csrf 토큰 삽입을 위해, 타임리프의 결과반환을 미룸.
  messages:
    basename: errorMessage
  jpa:
    hibernate:
      ddl-auto: create


mybatis:
  type-aliases-package: chat.twenty.domain
  mapper-locations: classpath:mapper/*.xml # resources/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  config: classpath:logback-local.xml


server:
  port: 5000
